PREFIX rt: <http://onto.fel.cvut.cz/ontologies/reporting-tool/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX aso: <http://onto.fel.cvut.cz/ontologies/aviation-safety/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

PREFIX er: <http://dev.inbas.cz/rdf4j-server/repositories/>
#PREFIX er: <http://localhost:48080/rdf4j-server/repositories/>

SELECT ?event_type ?event_type_iri ?year ?month (count(*) AS ?count) {
  {
    SELECT DISTINCT ?min {
      {
        SELECT (count(*) AS ?min) {
          [a aso:Occurrence]
          rt:has_event_type ?event_type_iri ;
          aso:has_start_time ?start_time .
          BIND(year(now()) AS ?thisYear)
          BIND(month(now()) AS ?thisMonth)
          BIND(year(?start_time) AS ?year)
          BIND(month(?start_time) AS ?month)
          FILTER (((?year + 1 = ?thisYear) && (?month >= ?thisMonth)) || (?year = ?thisYear))
        }
        GROUP BY ?event_type_iri
        ORDER BY desc(?min)
        LIMIT 5
      }
    }
  }
  {
    SELECT ?event_type_iri (count(*) AS ?cnt) {
      [a aso:Occurrence]
        rt:has_event_type ?event_type_iri ;
        aso:has_start_time ?start_time .
      BIND(year(now()) AS ?thisYear)
      BIND(month(now()) AS ?thisMonth)
      BIND(year(?start_time) AS ?year)
      BIND(month(?start_time) AS ?month)
      FILTER (((?year + 1 = ?thisYear) && (?month >= ?thisMonth)) || (?year = ?thisYear))
    }
    GROUP BY ?event_type_iri ?min
    ORDER BY desc(?cnt)

  }
  FILTER(?cnt = ?min)

  [a aso:Occurrence] rt:has_event_type ?event_type_iri ;
    aso:has_start_time ?start_time .
  BIND(year(now()) AS ?thisYear)
  BIND(month(now()) AS ?thisMonth)
  BIND(year(?start_time) AS ?year)
  BIND(month(?start_time) AS ?month)
  FILTER (((?year + 1 = ?thisYear) && (?month >= ?thisMonth)) || (?year = ?thisYear))

  OPTIONAL {
    SERVICE er:eccairs-aviation-3.4.0.2 {
      ?event_type_iri rdfs:label ?event_type.
    }
  }
  OPTIONAL {
    SERVICE er:inbas-model-2016-01-21:22-46-17 {
      ?event_type_iri rdfs:label ?event_type.
    }
  }
#   BIND(?event_e_t AS ?event_type)
}
GROUP BY ?year ?month ?event_type ?event_type_iri
ORDER BY ?year ?month desc(?count) asc(?event_type)