PREFIX rt: <http://onto.fel.cvut.cz/ontologies/reporting-tool/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX aso: <http://onto.fel.cvut.cz/ontologies/aviation-safety/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX doc: <http://onto.fel.cvut.cz/ontologies/documentation/>

PREFIX er: <http://dev.inbas.cz/rdf4j-server/repositories/>
PREFIX e-a-3_4_0_2-a-431: <http://onto.fel.cvut.cz/ontologies/eccairs/aviation-3.4.0.2/vl-a-431/>

SELECT ?year ?month ?severityAssessmentLabel (count(DISTINCT ?occurrence) AS ?count)
{
  ?occurrence a aso:Occurrence .
  OPTIONAL {
    ?occurrence aso:has_start_time ?start_time .
  }
  OPTIONAL {
    ?occurrence aso:has_end_time ?end_time .
  }
  OPTIONAL {
    ?rO doc:documents ?occurrence;
        doc:has_severity_assessment ?severityAssessment .
    SERVICE <http://dev.inbas.cz/rdf4j-server/repositories/eccairs-aviation-3.4.0.2> {
        ?severityAssessment rdfs:label ?severityAssessmentLabel .
    }
  }
  BIND ( month(?start_time) AS ?month )
  BIND ( year(?start_time) AS ?year )
#  BIND ( concat(str(?year),concat("/",str(?month))) AS ?year_month)
}
GROUP BY ?year ?month ?severityAssessment ?severityAssessmentLabel
ORDER BY ASC(?year) ASC(?month)